// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "ankurah-app.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface AnkurahApp : NSObject <NativeAnkurahAppSpec>
#else
#import <React/RCTBridgeModule.h>

@interface AnkurahApp : NSObject <RCTBridgeModule>
#endif

@end