// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "ankurah-app.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface {{project-name | pascal_case}} : NSObject <Native{{project-name | pascal_case}}Spec>
#else
#import <React/RCTBridgeModule.h>

@interface {{project-name | pascal_case}} : NSObject <RCTBridgeModule>
#endif

@end