// Generated by uniffi-bindgen-react-native
import installer from './Native{{project-name | pascal_case}}';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/ankurah_core';
export * from './generated/ankurah_proto';
export * from './generated/{{crate_name}}_bindings';
export * from './generated/{{crate_name}}_model';
export * from './generated/ankurah_signals';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as ankurah_core from './generated/ankurah_core';
import * as ankurah_proto from './generated/ankurah_proto';
import * as {{crate_name}}_bindings from './generated/{{crate_name}}_bindings';
import * as {{crate_name}}_model from './generated/{{crate_name}}_model';
import * as ankurah_signals from './generated/ankurah_signals';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  ankurah_core.default.initialize();
  ankurah_proto.default.initialize();
  {{crate_name}}_bindings.default.initialize();
  {{crate_name}}_model.default.initialize();
  ankurah_signals.default.initialize();
  initialized = true;
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

// Export the crates as individually namespaced objects.
export default {
  ankurah_core,
  ankurah_proto,
  {{crate_name}}_bindings,
  {{crate_name}}_model,
  ankurah_signals,
};

