// Generated by uniffi-bindgen-react-native
#include "ankurah-app.h"
#include "generated/ankurah_core.hpp"
#include "generated/ankurah_proto.hpp"
#include "generated/{{crate_name}}_bindings.hpp"
#include "generated/{{crate_name}}_model.hpp"
#include "generated/ankurah_signals.hpp"

namespace ankurahapp {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeAnkurahCore::registerModule(runtime, callInvoker);
		NativeAnkurahProto::registerModule(runtime, callInvoker);
		NativeAnkurahRnBindings::registerModule(runtime, callInvoker);
		NativeAnkurahRnModel::registerModule(runtime, callInvoker);
		NativeAnkurahSignals::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}