// Generated by uniffi-bindgen-react-native
#include "ankurah-app.h"
#include "generated/ankurah_rn_bindings.hpp"

namespace ankurahapp {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeAnkurahRnBindings::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}